version: "2"

services:
  reverse-proxy:
    build:
      context: tools/docker/reverse-proxy
    volumes:
    - ./tools/docker/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    - reverse-proxy-cert:/etc/pki/tls
    depends_on:
    - web
    - realtime

  web:
    image: enalean/tuleap-aio-dev:c6-php56-nginx
    volumes:
    - .:/usr/share/tuleap
    - ../tuleap-plugins:/usr/share/tuleap-plugins
    - tuleap-data:/data
    - realtime-cert:/etc/pki/ca-trust/source/anchors
    env_file:
    - .env
    depends_on:
    - ldap
    - db
    - realtime

  realtime:
    build:
      context: tools/docker/realtime
    command: /tuleap/tools/docker/realtime/run.sh
    volumes:
      - .:/tuleap:ro
      - realtime-conf:/etc/tuleap-realtime
      - realtime-cert:/published-certificate
    env_file:
      - .env

  mailhog:
    image: mailhog/mailhog

  ldap:
    image: enalean/ldap
    env_file:
    - .env
    volumes:
    - ldap-data:/data

  gerrit:
    container_name: tuleap-gerrit
    image: enalean/gerrit-tuleap:2.12
    volumes:
    - gerrit-data:/home/gerrit
    env_file:
    - .env
    depends_on:
    - ldap
    - db

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
    - jenkins-data:/var/jenkins_home

  db:
    image: mysql:5.5
    env_file:
    - .env
    volumes:
    - db-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.6
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  prometheus:
    image: prom/prometheus:v2.3.0
    volumes:
      - .metrics_secret.key:/metrics_secret.key
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus

  ldap-admin:
    image: osixia/phpldapadmin:0.7.1
    volumes:
      - ldap-data:/data
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap

volumes:
  tuleap-data:
  ldap-data:
  gerrit-data:
  db-data:
  rabbitmq-data:
  redis-data:
  realtime-conf:
  realtime-cert:
  reverse-proxy-cert:
  prom-data:
  jenkins-data:
