# Angular
[[IgnoredVulns]]
id = "GHSA-m2h2-264f-f486" # CVE-2022-25844
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

[[IgnoredVulns]]
id = "GHSA-prc3-vjfx-vhm9" # CVE-2022-25869
reason = "Angular is EOL. XSS can only be trigerred with IE. IE users would not be able to load the JS of Angular app in Tuleap."

[[IgnoredVulns]]
id = "GHSA-2qqx-w9hr-q5gx" # CVE-2023-26117
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

[[IgnoredVulns]]
id = "GHSA-2vrf-hf26-jrp5" # CVE-2023-26116
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

[[IgnoredVulns]]
id = "GHSA-qwqh-hm9m-p5hr" # CVE-2023-26118
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

[[IgnoredVulns]]
id = "GHSA-4w4v-5hc9-xrr2" # CVE-2024-21490
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

[[IgnoredVulns]]
id = "GHSA-m9gf-397r-hwpg" # CVE-2024-8372
reason = "Angular is EOL. No usage of the allowlist imgSrcSanitizationTrustedUrlList."

[[IgnoredVulns]]
id = "GHSA-mqm9-c95h-x2p6" # CVE-2024-8373
reason = "Angular is EOL. No usage of the allowlist imgSrcSanitizationTrustedUrlList."

[[IgnoredVulns]]
id = "GHSA-4p4w-6hg8-63wx" # CVE-2025-2336
reason = "Angular is EOL. No usage of the allowlist imgSrcSanitizationTrustedUrlList."

[[IgnoredVulns]]
id = "GHSA-j58c-ww9w-pwp5" # CVE-2025-0716
reason = "Angular is EOL. Small impact for our use cases."

# angular-gettext-cli / angular-gettext-loader
## nth-check
[[IgnoredVulns]]
id = "GHSA-rp65-9cf3-cjxr" # CVE-2021-3803
reason = "Angular and associated tools are EOL. Only used at build time. ReDoS."

## lodash.pick
[[IgnoredVulns]]
id = "GHSA-p6mc-m468-83gw" # CVE-2020-8203
reason = "Angular and associated tools are EOL. Only used at build time. Prototype Pollution cannot be exploited in our context."

# Angular ng-cache-loader
## html-minifier
[[IgnoredVulns]]
id = "GHSA-pfq8-rq6v-vf5m" # CVE-2022-37620
reason = "Angular and associated tools are EOL. Only used at build time. ReDoS."

# ckeditor4
[[IgnoredVulns]]
id = "GHSA-fq6h-4g8v-qqvm" # CVE-2024-24815
reason = "Vuln cannot be triggered: fullpage editing is not enabled and CDATA elements have not been enabled in the Advanced Content Filtering configuration."

[[IgnoredVulns]]
id = "GHSA-wh5w-82f3-wrxh" # CVE-2023-4771
reason = "ckeditor4 samples are not shipped."

[[IgnoredVulns]]
id = "GHSA-mw2c-vx6j-mg76" # CVE-2024-24816
reason = "ckeditor4 samples are not shipped."

[[IgnoredVulns]]
id = "GHSA-7r32-vfj5-c2jv" # CVE-2024-43407
reason = "ckeditor4 code snippet GeSHi."

# word-wrap
[[IgnoredVulns]]
id = "GHSA-j8xg-fqg3-53r7" # CVE-2023-26115
reason = "ReDoS. No direct impact in our situation."

# node-gettext
[[IgnoredVulns]]
id = "GHSA-g974-hxvm-x689" # CVE-2024-21528
reason = "No exploitation path in the Tuleap context for this prototype pollution issue."

# brace-expansion, transitive dep of eslint, jest, vue3-gettext, etc.
[[IgnoredVulns]]
id = "GHSA-v6h2-p8h4-qcjw" # CVE-2025-5889
reason = "Fixed in v2.0.2 but advisory range does not take it into account."

# Restler
[[IgnoredVulns]]
id = "GHSA-rvmg-xc29-rvxf" # CVE-2017-15363
reason = "Code is not accessible in Tuleap context."

# xlsx
[[IgnoredVulns]]
id = "GHSA-4r6h-8v6p-xvw6" # CVE-2023-30533
reason = "Fixed in 0.19.3 but scanner is not correctly resolving our current version (0.20.2)"

[[IgnoredVulns]]
id = "GHSA-5pgg-2g8v-p4x9" # CVE-2024-22363
reason = "Fixed in 0.20.2 but scanner is not correctly resolving our current version (0.20.2)"

### TO BE FIXED

# wasmtime
## instant
[[IgnoredVulns]]
id = "RUSTSEC-2024-0384"
reason = "Not used in production, see https://github.com/bytecodealliance/wasmtime/issues/9591"
ignoreUntil = 2025-10-12

# Go standard library
[[IgnoredVulns]]
id = "GO-2025-3955" # CVE-2025-47910
reason = "No security impact for Tuleap, we do not use AddInsecureBypassPattern in http.CrossOriginProtection."
ignoreUntil = 2025-10-22
