# Angular
[[IgnoredVulns]]
id = "GHSA-m2h2-264f-f486" # CVE-2022-25844
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

[[IgnoredVulns]]
id = "GHSA-prc3-vjfx-vhm9" # CVE-2022-25869
reason = "Angular is EOL. XSS can only be trigerred with IE. IE users would not be able to load the JS of Angular app in Tuleap."

[[IgnoredVulns]]
id = "GHSA-2qqx-w9hr-q5gx" # CVE-2023-26117
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

[[IgnoredVulns]]
id = "GHSA-2vrf-hf26-jrp5" # CVE-2023-26116
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

[[IgnoredVulns]]
id = "GHSA-qwqh-hm9m-p5hr" # CVE-2023-26118
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

[[IgnoredVulns]]
id = "GHSA-4w4v-5hc9-xrr2" # CVE-2024-21490
reason = "Angular is EOL. Nothing in the codebase can trigger this ReDoS issue."

# angular-gettext-cli / angular-gettext-loader
## nth-check
[[IgnoredVulns]]
id = "GHSA-rp65-9cf3-cjxr" # CVE-2021-3803
reason = "Angular and associated tools are EOL. Only used at build time. ReDoS."

## lodash.pick
[[IgnoredVulns]]
id = "GHSA-p6mc-m468-83gw" # CVE-2020-8203
reason = "Angular and associated tools are EOL. Only used at build time. Prototype Pollution cannot be exploited in our context."

# ckeditor4
[[IgnoredVulns]]
id = "GHSA-fq6h-4g8v-qqvm" # CVE-2024-24815
reason = "Vuln cannot be triggered: fullpage editing is not enabled and CDATA elements have not been enabled in the Advanced Content Filtering configuration."

[[IgnoredVulns]]
id = "GHSA-wh5w-82f3-wrxh" # CVE-2023-4771
reason = "ckeditor4 samples are not shipped."

[[IgnoredVulns]]
id = "GHSA-mw2c-vx6j-mg76" # CVE-2024-24816
reason = "ckeditor4 samples are not shipped."

# src/additional-packages/wasmtime-wrapper-lib/Cargo.lock
## atty
[[IgnoredVulns]]
id = "RUSTSEC-2021-0145"
reason = "Windows only."

[[IgnoredVulns]]
id = "GHSA-g98v-hv3f-hcfr" # Same as RUSTSEC-2021-0145
reason = "Windows only."

## mach
[[IgnoredVulns]]
id = "RUSTSEC-2020-0168"
reason = "Only used when targetting macOS."

# word-wrap
[[IgnoredVulns]]
id = "GHSA-j8xg-fqg3-53r7" # CVE-2023-26115
reason = "ReDoS. No direct impact in our situation."

# unplugin-vue2-script-setup via the transitive dep @antfu/utils
[[IgnoredVulns]]
id = "GHSA-p2fh-2h23-6grg" # CVE-2023-2972
reason = "No impact in our situation, unplugin-vue2-script-setup will be removed when the Vue 2 migration is completed."

# @vue/vue2-jest & vue-loader v15 via the transitive dep @vue/component-compiler-utils
## postcss
[[IgnoredVulns]]
id = "GHSA-7fh5-64p2-3v2j" # CVE-2023-44270
reason = "@vue/component-compiler-utils will be removed when the Vue 2 migration is completed."

### TO BE FIXED

# Nothing right now
